### ISSUE TITLE
Installation via Cocoapods

### ISSUE THREAD

**Issue by kmikael** [idnow/de.idnow.ios#1]
Installation should be possible simply via adding `pod IDnowSDK` to the project's *Podfile* and IDnow's dependencies should be dependencies of the `IDnowSDK` pod, so that installation doesn't require adding them to the project's `Podfile`.

See [bitstadium/HockeySDK-iOS](https://github.com/bitstadium/HockeySDK-iOS) for how this should be done.

**Comment by kmikael** [comment]
Update: See this OpenSSL Cocoapod for an example of making a Cocoapod from a static library. https://github.com/krzyzanowskim/OpenSSL

But a framework like `HockeySDK` seems to be better and easier

**Comment by macmacen** [comment]
We work on that. The possibility to integrate the IDnow SDK via Cocoapods will shortly follow.

**Comment by FGoessler** [comment]
Any update on this issue? Been a while since the 'shortly' statement 😁

**Comment by 0bmxa** [comment]
+1

**Comment by quifago** [comment]
any update?

**Comment by arminbauer** [comment]
Cocoapods is now officially supported since the 2.2.0 version. Was a bit more complex than initially expected... Sorry for the delay.

**Comment by kmikael** [comment]
We are not able to use the Cocoapods installation, because we need OpenSSL in our app and adding OpenSSL and IDnow via Cocoapods leads to conflicting symbols.

Example:

```
duplicate symbol _X509_CINF_it in:
    /Users/kmikael/Source/Company/Project/Pods/OpenSSL-Universal/lib-ios/libcrypto.a(x_x509.o)
    /Users/kmikael/Source/Company/Project/Pods/IDnowSDK/idnow-sdk/libidnow-sdk-universal.a(x_x509.o)
```

Obviously we get such a duplicate symbol for each OpenSSL header, a total of 40.

Previously, the a manual installation we didn't have these conflicts since OpenTok fixed the issue.

Are you using OpenSSL too now in addition to the one already in OpenTok? If sou can you add OpenSSL as a cocoapod dependency or use the tricks that OpenTok used (I do not know what they did).
