### ISSUE TITLE
cornerRadius property not documented?

### ISSUE THREAD

**Issue by thirtified** [idnow/de.idnow.ios#116]
The Changelog mentions the introduction of a `cornerRadius` customization option, but it doesn't seem to be mentioned in the documentation. Is this option available, and if so, could you add documentation for it (what does it affect, just buttons or also input field corners)?

Thanks,
\- Julian

**Comment by pavel-antonov-idnow** [comment]
Hi @thirtified there is `textFieldCornerRadius` parameter to control  input field corners
