### ISSUE TITLE
`use_frameworks! :linkage => :static`

### ISSUE THREAD

**Issue by reichhartd** [idnow/de.idnow.ios#119]
Hello together,

I'm the maintainer of the library [@tokenstreet/react-native-idnow-videoident](https://github.com/tokenstreet-tech/react-native-idnow-videoident).

Currently there is only the possibility to use this SDK with the option `use_frameworks! :linkage => :static`.
This creates especially in connection with React Native errors, for example with `sentry-react-native` (https://github.com/getsentry/sentry-react-native/issues/2353), and currently, this keeps us from integrating `react-native-skia` (https://github.com/Shopify/react-native-skia/issues/652).

Is there a way to release this SDK without the constraint of this link type?

This would help us a lot.

**Comment by jfaq89** [comment]
We're having the same problem. Is there a workaround?

**Comment by adeem** [comment]
any update here?

**Comment by pavel-antonov-idnow** [comment]
Hi @reichhartd , @jfaq89 , @adeem  cannot say a lot about the specific date, hopefully early next year,  we have plans to release the sdk as XCFramework so it shouldn't have the mentioned configuration
