### ISSUE TITLE
There are hundreds of warnings generated by our app after the latests IDnow SDK update

### ISSUE THREAD

**Issue by kmikael** [idnow/de.idnow.ios#12]
Apparently, these are generated by the `dSYM`, according to Xcode. Can you check it out, @macmacen? I think you might have accidentally added fixed paths to the SDK which Xcode cannot find on our machines.

![screen shot 2015-10-05 at 11 49 27](https://cloud.githubusercontent.com/assets/1111937/10277600/50ddc7ec-6b57-11e5-8126-a47907385897.png)

**Comment by macmacen** [comment]
Should be fixed in current release (de.idnow.ios-1.5.1)

**Comment by kmikael** [comment]
Sadly, the issue is not fixed in the latest version… Here is a screenshot of the warnings now:

<img width="1080" alt="screen shot 2015-11-11 at 00 04 23" src="https://cloud.githubusercontent.com/assets/1111937/11090269/f1c9a582-8870-11e5-93e2-8c5ca641317a.png">

**Comment by arminbauer** [comment]
@kmikael Should be fixed now, can you please check?

**Comment by kmikael** [comment]
Just, checked. It hasn't been fixed yet. We're back at fixed @macmacen paths.

![screen shot 2015-11-16 at 11 38 52](https://cloud.githubusercontent.com/assets/1111937/11179862/b3fc1052-8c56-11e5-8406-af987135d796.png)

**Comment by macmacen** [comment]
@kmikael: I have re-built the SDK and tested it with a separate user. It now seems to work.
Can you check out branch "mre/12_warnings_dsym" and verify if its now working properly?

Note: If not already present you have to add "Webkit.framework" and "Accelerate.framework" to your "Link binary with libraries" section.

**Comment by kmikael** [comment]
👍🏻🎉 The warnings are gone!

I also needed to remove the module map file, otherwise Xcode cannot find `IDnowSDK.h`.

Just out of curiosity:

- What was the issue and how did you fix it?
- Does it have something to do with `WebKit` and `Accelerate`? Or do we just need to add them to the project now for other reasons?
- What was your intention with the module map file? That one can use `@import IDnowSDK;`?

**Comment by arminbauer** [comment]
This should now be fixed in https://github.com/idnow/de.idnow.ios/releases/download/de.idnow.ios-2.0.0-RC.2/idnow-ios-2.0.0-RC.2.zip. Yes, it seems it was related to Webkit and Accelerate.
