### ISSUE TITLE
"Unable to read the license file idnow-sdk/LICENSE.md for the spec IDnowSDK (5.1.12)" during pod install

### ISSUE THREAD

**Issue by PatrickDotStar** [idnow/de.idnow.ios#121]
The license file in [IDnowSDK.podspec](https://github.com/CocoaPods/Specs/blob/master/Specs/b/2/e/IDnowSDK/5.1.12/IDnowSDK.podspec.json) is currently targeting to `idnow-sdk/LICENSE.md` however the folder `idnow-sdk` does no longer exist and the `LICENSE.md` file is now in the root folder.\
So this needs to be changed to:

```
"license": {
  "type": "Commercial",
  "file": "LICENSE.md"
},
```

**Comment by pavel-antonov-idnow** [comment]
@PatrickDotStar thank you for mentioning the case

**Comment by nholloh** [comment]
Is there any progress on this?

**Comment by pavel-antonov-idnow** [comment]
@PatrickDotStar @nholloh just updated with last 6.1.4 release
