### ISSUE TITLE
Cannot find idNow-sdk folder to install manually

### ISSUE THREAD

**Issue by KhoaND12** [idnow/de.idnow.ios#122]
Hi,

Sorry but i cannot find the idNow-sdk folder as you said from release source. Its just have eid framework inside. 

Can you guide me how to get idNow-sdk framework folder?

Thanks,

**Comment by pavel-antonov-idnow** [comment]
Hi @KhoaND12 you can download the sdk from releases on right side of the https://github.com/idnow/de.idnow.ios page
