### ISSUE TITLE
bitcode support: "bitcode bundle could not be generated"

### ISSUE THREAD

**Issue by dock13** [idnow/de.idnow.ios#14]
When building an archive I receive the following message:
`ld: bitcode bundle could not be generated because '../de.idnow.ios/idnow-sdk/libidnow-sdk-universal.a(IDNRoundedView.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64 clang: error: linker command failed with exit code 1 (use -v to see invocation)`
Could you provide a library with bitcode support?

**Comment by arminbauer** [comment]
We will check if this is possible and what this means for the size of sdk. At the moment we distribute the SDK through github and if the size gets bigger we might quickly hit the 100mb limit. So a switch to cocoa pods might be necessary as a first step.

**Comment by arminbauer** [comment]
You can find the lastest version with bitcode support at https://github.com/idnow/de.idnow.ios/releases/download/de.idnow.ios-2.0.0-RC.2/idnow-ios-2.0.0-RC.2.zip. Please note: While we fully support bitcode in our project, Tokbox does not yet. You need to include a beta version of the Tokbox libraries.

You can see how this is done here: https://github.com/idnow/de.idnow.ios/tree/releases/2.0. Also, you can find a bitcode sample project under Sample-Bitcode/
