### ISSUE TITLE
Error when compiling Sample project

### ISSUE THREAD

**Issue by quifago** [idnow/de.idnow.ios#20]
Hi,
When trying to compile the Sample project, I receive the following errors:
<img width="304" alt="screen shot 2016-04-27 at 17 21 58" src="https://cloud.githubusercontent.com/assets/2972550/14857437/963a4626-0c9c-11e6-87ca-0b1276931b47.png">

Log:
```
ld: LTO remark: silk/decode_core.c:174:13: loop not vectorized: cannot prove it is safe to reorder memory operations
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang emitted errors but did not return a nonzero exit code to indicate failure
```

**Comment by arminbauer** [comment]
This has been fixed in 2.2.0
