### ISSUE TITLE
Plans for React-Native Support

### ISSUE THREAD

**Issue by nirshubz** [idnow/de.idnow.ios#28]
I was wondering if you have any plans to support react-native? 

Thanks!

**Comment by hkretzschmar** [comment]
Hi nirshubz,

supporting hybrid frameworks has not been the top priority for providing our SDK in the beginning stages, but in the last couple of months we have been asked for support regarding hybrid platforms like Xamarin, React and Cordova. Since we see the need of our customers to support these frameworks we are at the moment discussing internally how and when we will do that and which frameworks will get offically supported. I can tell you that we already have customers who successfully integrated the current SDK into Cordova.

Any new SDK platform will be announced here: [https://www.idnow.eu/developers](https://www.idnow.eu/developers)

Kind regards
Holger Kretzschmar

**Comment by yogiben** [comment]
@hkretzschmar Please prioritise React Native.

**Comment by flippinloud** [comment]
Hi @hkretzschmar, can you give me any further information on the progress of Xamarin support please?

**Comment by hkretzschmar** [comment]
Hi @yogiben @flippinloud 
the status of supporting hybrid frameworks has not changed, meaning that we still have it on the backlog but not planned to implement this in the near future. As stated earlier it is possible to use the current native SDK in conjunction with Corova, React or Xamarin.
Kind regards

**Comment by rkahle** [comment]
Do you have any tips or examples how to integrate the sdk in a React Native environment? We had no problems integrating the android sdk, but unfortunately can't get it working on iOS.

**Comment by kbarzen-idn** [comment]
Hello @rkahle,

Maybe this helps you: https://hub.packtpub.com/using-native-sdks-and-libraries-react-native/

Kind regards,

Kay

**Comment by j-steel** [comment]
The solution is to get the current ViewController and pass it to the IDNowSDK. You can use the code provided in the ViewController @ IDNow Example in your RCT_EXPORT_METHOD and replace self variable with the current VC:
`//get current viewController to render idNow Stuff
    UIViewController * viewController = [[[UIApplication sharedApplication] delegate] window].rootViewController;
//init idNowController
    IDnowController *idNowController = [[IDnowController alloc] initWithSettings: settings];

//start your stuff
[idNowController initializeWithCompletionBlock:^(BOOL success, NSError * _Nullable error, BOOL canceledByUser)
    {
        if ( success )
        {
            // Start identification using blocks
            [idNowController startIdentificationFromViewController:viewController withCompletionBlock:^(BOOL success2, NSError * _Nullable error, BOOL canceledByUser)
             {...}
         }
}];
`
i think this should help when trying to get the Native component working.

**Comment by yogiben** [comment]
Has anyone successfully done this or knows someone who can get this done?

**Comment by j-steel** [comment]
Hi @yogiben, i was able to get it to work with the code provided above and adding idnow to the native project opened with xcode as an project.

**Comment by LukaGiorgadze** [comment]
@nirshubz @yogiben @rkahle 

### Integration on iOS:
**1. Add pod into ro /ios/ folder**

- `pod init` and then open newly created Podfile:

``` 
...
 // remove duplicated tvOSTests form pod
...
target 'idnowReact' do // replace idnowReact with your project name
  use_frameworks! // uncomment
  pod 'IDnowSDK' // add pod
...
```
- pod install

**2. Open .xcworkspace and Add dependencies**
idnowReact (It's my project name) -> Targets (idnowReact) -> Build Phases -> Link Binary With Libraries:
Accelerate
AudioToolBox
AVFoundation
CoreMedia
GLKit
OpenGLES
WebKit
libz.dylib
See image: [https://ibb.co/QCc7fHS](https://ibb.co/QCc7fHS)

**3. Add required files in ios directory:**
```
// IDnowSettingsPrivate.h

#import "IDnowSettings.h"
@interface IDnowSettings ()
@property (assign, nonatomic) BOOL ignoreCompanyID;
@end
```

```
// IDnowViewManager.h

#import <UIKit/UIKit.h>
#import <React/RCTBridgeModule.h>
#import <React/RCTViewManager.h>
#import "IDnowSettingsPrivate.h"
@import IDnowSDK;
@interface IDnowViewController : UIViewController
@end
@interface IDnowViewManager : RCTViewManager
@end
```

```
IDnowViewManager.m

#import <React/RCTBridgeModule.h>
#import "IDnowViewManager.h"

static NSString *const COMPANY_ID_VIDEO_IDENT = @"_YOUR_COMPANY_ID"; // change it
static NSString *token = @"TST-XXXXX"; // don't change

@interface IDnowViewController () <IDnowControllerDelegate>
@property (strong, nonatomic) IDnowController *idnowController;
@property (strong, nonatomic) IDnowSettings   *settings;
@end


//-------------------------------------------------------//
//-------------------------------------------------------//
//-------------------------------------------------------//
@implementation IDnowViewController

#pragma mark - View lifecycle -
- (void) viewDidLoad
{
  [super viewDidLoad];
  
  // Set up and customize settings
  self.settings = [IDnowSettings new];
  self.settings.showErrorSuccessScreen = true;
  self.settings.showVideoOverviewCheck = false;
  self.settings.ignoreCompanyID        = true;
  
  // Set up IDnowController
  self.idnowController = [[IDnowController alloc] initWithSettings: self.settings];
  
  // Appearance
  UIColor *color = [UIColor colorWithRed:212.0/255.0 green:14.0/255.0 blue:20.0/255.0 alpha:1.0];
  IDnowAppearance *appearance = [IDnowAppearance sharedAppearance];
  
  appearance.defaultTextColor              = color;
  appearance.primaryBrandColor             = color;
  appearance.proceedButtonBackgroundColor  = color;
  appearance.failureColor                  = [UIColor redColor];
  appearance.successColor                  = [UIColor greenColor];
  appearance.enableStatusBarStyleLightContent = YES;
  
  // Start video identification in view did load
  [self startVideoIdent: token];
}

#pragma mark - IBActions -

- (IBAction) startVideoIdent: (id) sender
{
  // assign token and company id
  self.settings.transactionToken = token;
  self.settings.companyID = COMPANY_ID_VIDEO_IDENT;
  
  self.idnowController.delegate  = nil;
  __weak typeof(self) weakSelf   = self;
  
  // Initialize identification using blocks (alternatively you can set the delegate and implement the IDnowControllerDelegate protocol)
  [self.idnowController initializeWithCompletionBlock:^(BOOL success, NSError * _Nullable error, BOOL canceledByUser)
   {
     if ( success )
     {
       [weakSelf.idnowController startIdentificationFromViewController:self withCompletionBlock:^(BOOL success, NSError * _Nullable error, BOOL canceledByUser)
        {
          if ( success )
          {
          }
          else
          {
          }
        }];
     }
     else if ( error )
     {

       UIAlertController *alertController = [UIAlertController alertControllerWithTitle: @"Error" message: error.localizedDescription preferredStyle: UIAlertControllerStyleAlert];
       UIAlertAction *action = [UIAlertAction actionWithTitle: @"Ok" style: UIAlertActionStyleCancel handler: nil];
       [alertController addAction: action];
       [weakSelf presentViewController: alertController animated: true completion: nil];
     }
   }];
}

#pragma mark - IDnowControllerDelegate -
- (void) idnowController: (IDnowController *) idnowController initializationDidFailWithError: (NSError *) error
{
  UIAlertController *alertController = [UIAlertController alertControllerWithTitle: @"Error" message: error.localizedDescription preferredStyle: UIAlertControllerStyleAlert];
  UIAlertAction    *action       = [UIAlertAction actionWithTitle: @"Ok" style: UIAlertActionStyleCancel handler: nil];
  [alertController addAction: action];
  [self presentViewController: alertController animated: true completion: nil];
}

- (void) idnowControllerDidFinishInitializing: (IDnowController *) idnowController
{
  [self.idnowController startIdentificationFromViewController: self];
}

- (void) idnowControllerCanceledByUser: (IDnowController *) idnowController
{
}

- (void) idnowController: (IDnowController *) idnowController identificationDidFailWithError: (NSError *) error
{
}

- (void) idnowControllerDidFinishIdentification: (IDnowController *) idnowController
{
}

#pragma mark - Memory Management -
- (void) didReceiveMemoryWarning
{
  [super didReceiveMemoryWarning];
  // Dispose of any resources that can be recreated.
}
@end




//-------------------------------------------------------//
//-------------------------------------------------------//
//-------------------------------------------------------//
@implementation IDnowViewManager {
  IDnowViewController* vc;
}

- (dispatch_queue_t)methodQueue {
  return dispatch_get_main_queue();
}

RCT_EXPORT_MODULE();

RCT_EXPORT_METHOD(setToken:(NSString *)_token) {
  token = _token;
}

- (UIView *)view {
  return [[[IDnowViewController alloc] init] view];
}
@end

```

**4. Javascript**
```
const IDnowModule = NativeModules.IDnowViewManager;
const IDnowComponent = requireNativeComponent('IDnowView', null);
```

// Set token
`IDnowModule.setToken("TST_EXAMPLE_TOKEN");`

`// This is idnow view: <IDnowComponent /> `

P.S. I'll write for Android later :)

**Comment by NazarYablonskiy** [comment]
https://github.com/bitwala/react-native-idnow
have fun ;)

**Comment by givehug** [comment]
Hi, still in the backlog? Would be nice to have an official library for ReactNative?
