### ISSUE TITLE
Invalid static library binary

### ISSUE THREAD

**Issue by adebt** [idnow/de.idnow.ios#29]
xcrun -sdk iphoneos lipo -info libidnow-sdk-universal.a 
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't figure out the architecture type of: libidnow-sdk-universal.a

Version 3.1.1
Could you please fix it.

**Comment by hkretzschmar** [comment]
Hi adebt,

sorry for the late answer, I just checked with the version you posted this for and the most current and the lipo tool returns the following architectures for the IDnow SDK

```
hkr$ xcrun -sdk iphoneos lipo -info libidnow-sdk-universal.a
Architectures in the fat file: libidnow-sdk-universal.a are: i386 armv7 armv7s x86_64 arm64 
```

Kind regards
Holger

**Comment by digitalwert-developer** [comment]
Hi,

I'm having the exact same problem, sdk version 3.15.0.
Any idea?

Kind regards
