### ISSUE TITLE
SDK opens Safari with the callback that the user has cancelled the verification

### ISSUE THREAD

**Issue by martindaum** [idnow/de.idnow.ios#32]
When the screen of the idnow SDK is shown and I tap on the cancel button on the upper left side and cancel the verification, the SDK opens Safari with the callback url. The completion-block or the delegate method of the native SDK gets also called. I do not want the SDK to open Safari in that case. 

Is there a setting for this or can this be fixed in the next version?

**Comment by andreaskofer** [comment]
Hello,

please get in touch with your contact person at IDnow. This is a setting which needs to be changed on the backend for your account. Once this has been done Safari will not be opened anymore.

Best regards,
Andreas
