### ISSUE TITLE
iOS SDK launches Safari webpage after finish identification

### ISSUE THREAD

**Issue by quifago** [idnow/de.idnow.ios#34]
Hi,

We are facing a problem in the iOS app. We have a callback defined in our IDNow configuration (backend side) to redirect the users to our sign in page once they have legitimated. 
However, this callback was thought for the web legitimation, it has not point to launch it when you are using iOS SDK.
In Android SDK the callback is not fired.

Is this an iOS bug?
Is there anyway to block this callback for iOS at the SDK configuration? or in backend configuration?

Thanks

**Comment by andreaskofer** [comment]
Hello,

the behaviour of the SDK regarding the redirects is determined by the backend configuration. Please get in touch with your IDnow representative to have this configuration adjusted.

Thank you and best regards,
Andreas
