### ISSUE TITLE
Push instead of modal presentation

### ISSUE THREAD

**Issue by martindaum** [idnow/de.idnow.ios#35]
We show the verification in a form-sheet on the iPad. Whatever I do, the idnow-controller always shows up modally and is using the fullscreen. I would either want it to be pushed on my existing navigation-controller or also have it displayed within a form-sheet. I tried playing around with the forceModalPresentation and modalPresentationStyle properties of the settings, but there is no effect whatever I change them to.

Could you provide some detailed documentation what has to be done?

Thanks!

**Comment by aare-undo-idnow** [comment]
Closing as it no longer seems relevant. It's been four years and Apple has reworked its modal presentation style several times since then.
