### ISSUE TITLE
SDK size of 344MB is way too large

### ISSUE THREAD

**Issue by orschaef** [idnow/de.idnow.ios#37]
When using cocoapods our common strategy is to check in all pods. 

That's a good idea, because there have already been numerous cases where dependencies disappeared and then your project will never build.
Of course there are many discussion about "check in pods or not" but I think there are many developers out there who think the same.

Since git does not work very well with binaries pushing 344MB to the VCS is a non-acceptable circumstance. As soon as the library is updated git will re-upload 344MB and so the repository size grows like crazy. This also leads to a slowed down workflow on every commit/push.

What is your recommendation on this? Do you have any solutions for this problem?

**Comment by hkretzschmar** [comment]
Hi orschaef,

the IDnow SDK comes in the form of a so called fat binary. That means it contains the code and 3rd party libraries we use for all supported platforms including the simulator. If you build an app with the SDK and check the size of the resulting app for a single platform you will notice that this 344MB will be reduced to around 16MB.

Kind regards
Holger
