### ISSUE TITLE
Manual setup is not a manual setup

### ISSUE THREAD

**Issue by orschaef** [idnow/de.idnow.ios#38]
Since it is a requirement to use cocoapods your documentation about the "Manual installation of IDnow" is a bit misleading.

When you have cocoapods installed you just use `pod 'IDnowSDK'` - no need to install the dependencies via cocoapods.

Maybe you should change the documentation.

**Comment by hkretzschmar** [comment]
Hi orschaef,

yes true to wording might not be the best, but since we have a lot of customers using the SDK without CocoaPods it is absolutley possible to add the IDnow SDK manually to your project. We will update the documentation accordingly with the next release.

Kind regards
Holger
