### ISSUE TITLE
Support for IDNow in UI testing

### ISSUE THREAD

**Issue by quifago** [idnow/de.idnow.ios#39]
I would like to know if IDNow has some kind of setting to be able to run it on simulator for our integration tests.
Ideally, even bypassing all video controller that takes around 5 min.

On devices, we are using the option 'X-MANUALTEST-HAPPYPATH'. 
Can you tell me if exist any other 'tweak' to be able to run IDNow in simulators, or even bypassing the video process? 

Thanks.

**Comment by andreaskofer** [comment]
Hello,

in case you want to test backend functionality only, you can use the X-AUTOTEST-* tests.

If you need further support, please use our ticketing system at https://support.idnow.de

Thank you and best regards,
Andreas
