### ISSUE TITLE
Only Generic Archives with Xcode 9.3

### ISSUE THREAD

**Issue by devtribe** [idnow/de.idnow.ios#40]
If i archive the project with XCode 9.3 it will generate only a generic archive which i can't upload to the App Store. Also with your Sample Project.

**Comment by andreaskofer** [comment]
Hello,

I think you also raised this issue in our Service Desk. We are looking into this and will give you feedback via our Service Desk.

Best regards,
Andreas

**Comment by tja** [comment]
I run into the same problem. I wouldn't mind moving the discussion back to GitHub so everyone can follow.

**Comment by hkretzschmar** [comment]
Hi tja,

sorry for the very late answer. Yes you are right there is an issue regarding cocoapods and the resource bundles. We found out that depending on the build order resources could go missing either from the host app or the SDK. To mitigate that we came up with an addition to the Podfile which can be found in the README: https://github.com/idnow/de.idnow.ios#cocoapods--xcode-9

Kind regards
Holger

**Comment by tja** [comment]
Thanks for your reply, @hkretzschmar.

However, please be aware that the fix you're mentioning does _not_ work with CocoaPods 1.5.0 (please try for yourself)! They have their own mitigation for the very same issue, and your fix and CocoaPods' mitigation step on each others toes. Unfortunately, the mitigation in CocoaPods 1.5.0 is faulty, as I explained in my previous post, and the fix they have (in master) had to be applied manually.

I would recommend that you change your README instructions accordingly.

**Comment by aare-undo-idnow** [comment]
This no longer seems relevant, closing
