### ISSUE TITLE
Prefill user phone number

### ISSUE THREAD

**Issue by sasha-tomorrow** [idnow/de.idnow.ios#44]
It is not possible to prefill user phone number. It leads to the situation, when user has to enter his/her phone number several times. E.g. one for sign up and one more time for IDNow.

Would be nice to have an option to prefill the phone number for the user.

**Comment by andreaskofer** [comment]
Hello Sasha,

it is possible to prefill the phone number. You can create an identification (eg by using our REST API) and pass the phone number. Once the user then starts this identification, the phone number is already prefilled.

You can find our API docu here: https://www.idnow.eu/development/api-documentation/

You can also ask for support at https://support.idnow.de where we can provide support specific to your configuration.

Best regards,
Andreas
