### ISSUE TITLE
When running the sample app it crashes

### ISSUE THREAD

**Issue by sichy** [idnow/de.idnow.ios#45]
Simply getting the SDK, update the pods (pod install) and running it on device. No updates to the demo source code and app just crashes when tapping on "Start Video Intent"

Error is in processing the response to call to: https://api.dev.idnow.de/api/v1/DEV-XSXQK

Error is: error	NSError *	domain: @"com.alamofire.error.serialization.response" - code: 18446744073709550605	0x00000001c04567d0

Screenshot of my XCode debug session: https://cl.ly/3Q1a2g0t0r2R

-Pavel

**Comment by aare-undo-idnow** [comment]
No longer topical
