### ISSUE TITLE
Multiple Targets did not show correct Assets.xcassets for per target

### ISSUE THREAD

**Issue by vantangst** [idnow/de.idnow.ios#47]
Hi everybody, I have a problem after implementing IDnow.
My app supports multiple Targets. There are 3 targets and 3 folder Assets.xcassets for per target.
After integrating IDnow, all targets only use one Assets.xcassets. I tried everything but it did not work well like before.
Ex for my problem after integrating IDnow:
  ```
target A use B.xcassets
  target B use B.xcassets
  target C use B.xcassets
```
Before integrating IDnow:
  ```
target A use A.xcassets
  target B use B.xcassets
  target C use C.xcassets
```
My project: https://github.com/vantangst/MultipleTargetIDNow
Any idea for this issue?
Thanks

**Comment by minhmera** [comment]
same issue , did someone solve this ?

**Comment by phu-idnow** [comment]
Hi @vantangst, @minhmera ,

This is a bug in cocoapods.
Reference: https://stackoverflow.com/a/21309102.
You can temporarily fix it by manual copy the SDK's assets.

And the IDNOW will fix it by using resource file instead of assets catalog.

Thanks,

**Comment by vantangst** [comment]
I found the solution for this issue:
We need put this script to `podfile` of cocoapods
I use cocoapods version 1.5.3
```
post_install do |installer_representation|
    # Pods-<target>-resources.sh to only handle target specific xcassert files.
    # orignal workaround found here: https://github.com/2359media/ios-dev-discussions/issues/7
    installer_representation.aggregate_targets.each do |at|
        files = at.user_targets.map{|t|
            t.resources_build_phase.files_references.select{|f|
                f.last_known_file_type == 'folder.assetcatalog'
            }.map{|f|
                Pathname.new(f.real_path).relative_path_from(f.project.path.dirname)
            }
        }.flatten
        script = at.copy_resources_script_path
        files = files.join('" "')
        `sed -i '' 's@OTHER_XCASSETS=.*@XCASSET_FILES+=(\"#{files}\")@' '#{script}'`
        `sed -i '' 's@OTHER_XCASSETS@XCASSET_FILES@' '#{script}'`
    end
end
```
Thanks

**Comment by vantangst** [comment]
> Hi @vantangst, @minhmera ,
> 
> This is a bug in cocoapods.
> Reference: https://stackoverflow.com/a/21309102.
> You can temporarily fix it by manual copy the SDK's assets.
> 
> And the IDNOW will fix it by using resource file instead of assets catalog.
> 
> <img alt="screen shot 2018-10-18 at 4 32 03 pm" width="1420" src="https://user-images.githubusercontent.com/42606414/47145558-36eaa280-d2f4-11e8-92c3-5c89b13715f9.png">
> 
> Thanks,
