### ISSUE TITLE
Don't use "and" in method names

### ISSUE THREAD

**Issue by kmikael** [idnow/de.idnow.ios#5]
`+ (instancetype)settingsWithCompanyID:(NSString *)companyID transactionToken:(NSString *))transactionToken;`

not

`+ (instancetype) settingsWithCompanyID: (NSString *) companyID andTransactionToken: (NSString *) transactionToken;`

**Comment by macmacen** [comment]
"and", "with", etc. are now eliminated from method names to improve swift compatibility.
Furthermore nonnull and nullable specifiers were added to the public headers.
