### ISSUE TITLE
UIUserNotificationSettings is deprecated

### ISSUE THREAD

**Issue by kenthumphries** [idnow/de.idnow.ios#50]
Hello!

I'm using IDNow SDK in a project with Xcode build setting _'Treat Warnings as Errors'_ enabled. I'm using CocoaPods, so any warning in my code (or IDNow pod) will trigger a compilation error.

**I wish to build the app with a deployment target of iOS 10.0.** However, this is not possible when including IDNow SDK and enabling _'Treat Warnings as Errors'_.

When I update the deployment target to iOS 10.0, I get a compilation warning for this line of IDnowAppDelegate.h:
`- (void)application:(UIApplication*)application  didRegisterUserNotificationSettings:(UIUserNotificationSettings*)notificationSettings;`

I get this warning (which is treated as an error):
`'UIUserNotificationSettings' is deprecated: first deprecated in iOS 10.0 - Use UserNotifications Framework's UNNotificationSettings`

Is there a plan to update this deprecated code?

Thank you very much.

**Comment by aare-undo-idnow** [comment]
Has been fixed for some time. Also, just as a general note, `Treat Warnings as Errors` is not really plausible when building a large-scale application with several dependencies.
