### ISSUE TITLE
Obtaining appState from a background thread

### ISSUE THREAD

**Issue by ghost** [idnow/de.idnow.ios#51]
It seems the app state is obtained from a background thread.
![image](https://user-images.githubusercontent.com/38656677/51472964-5114a080-1d7b-11e9-9ce1-1461f1c5c548.png)

SDK version: 3.15.0
iOS version: 12.1.2

**Comment by danielkiedrowski** [comment]
+1

**Comment by aare-undo-idnow** [comment]
Wow, this is pretty old. Sorry you experienced this and that no one from our side paid any attention, but definitely no longer the case, so closing in the context of housekeeping.
