### ISSUE TITLE
Extra characters in localizedDescription

### ISSUE THREAD

**Issue by sasha-tomorrow** [idnow/de.idnow.ios#52]
SDK 3.15.0

`IDnowErrorOfficeClosed` error has a `localizedDescription`. For some reason it contains an extra debugging information:
`IDNOW_ERROR_DESCRIPTION_1003_0 Daily: 8:00 to 24:00\n IDNOW_ERROR_DESCRIPTION_1003_0`

Do not see the reason for the prefix and suffix. Would be way easier if you can deliver just open hours: `Daily: 8:00 to 24:00`

**Comment by kbarzen-idn** [comment]
Hello @sasha-tomorrow,

This should be fixed in version 3.17.0.

Kind regards,

Kay
