### ISSUE TITLE
Speed test is broken

### ISSUE THREAD

**Issue by ghost** [idnow/de.idnow.ios#53]
We have quite some customers, that report problems with speed test. From time to time IDNow doesn't allow them to proceed to an identification, because of the internet speed. However, other applications show speed 50-100Mb. It is definitely enough for a video call.

OS: iOS 11-12
SDK: 3.15-3.18

Also, it seems, SDK doesn't support dynamic height of labels, so some are cut.

![image](https://user-images.githubusercontent.com/38656677/58433170-2edab880-80b6-11e9-92a6-14151e406969.png)

**Comment by phu-idnow** [comment]
Hi,
Maybe the network was not stable, did they try with another wifi, mobile data, ...?
and the dynamic height already supported, please check the latest version.

**Comment by danielkiedrowski** [comment]
We have that way too often as well. It especially acts up when the app is connected to the xcode debugger.

+1

**Comment by aare-undo-idnow** [comment]
There have been various improvements to the testing logic since this issue was first reported and it doesn't seen relevant any more. If it is, I'm very willing to have another look at this topic.

**Comment by albertovelazmoliner** [comment]
Speed test is broken again...
I'm testing on iPhone 13, with 700 mb download/800 mb upload and I got stuck in bad connectivity screen.


https://user-images.githubusercontent.com/1174318/204254425-13208a5a-94c2-4aa9-8c93-832e1711d846.MP4

**Comment by hansdesmedt** [comment]
We experience the same, very fast internet, iOS 16, iPhone 14 max, still getting this error.  Any solutions?

**Comment by barts2108** [comment]
200 MB connection here fixed line, fiber. Speedtest.net also says so 200/200 MBit. 

IDNow says 

It seems that we cannot test your internet connection speed at the moment. Please check to make sure your computer is connected to the internet and try again.
