### ISSUE TITLE
How to get rid of "rate us on Trustpilot" dialog?

### ISSUE THREAD

**Issue by NazarYablonskiy** [idnow/de.idnow.ios#55]

**Comment by phu-idnow** [comment]
Cannot disable/enable via SDK settings
it goes with customer config

**Comment by NazarYablonskiy** [comment]
Hey @phu-idnow,
how do I change the customer config? Is it possible?
Thank you for the response!

**Comment by phu-idnow** [comment]
hi @NazarYablonskiy ,
please create a ticket: support.idnow.io

**Comment by NazarYablonskiy** [comment]
ok, thank you
