### ISSUE TITLE
Crash on [FMIceLinkICEUdpMessageBroker load]

### ISSUE THREAD

**Issue by tjanela** [idnow/de.idnow.ios#59]
## Environment

Xcode 10.3
Swift 5
arm64 / iOS 12.4

##Dependencies

✅ Masonry - 1.1.0
✅ SocketRocket - 0.5.1
✅ AFNetworking - 3.2.1
✅ libPhoneNumber-iOS - 0.9
✅ FLAnimatedImage - 1.0.15
✅ Sentry - 4.3.4

These dependencies are being provided by carthage:

github "SnapKit/Masonry" == 1.1.0
github "AFNetworking/AFNetworking" == 3.2.1
github "iziz/libPhoneNumber-iOS" == 0.9.15
github "getsentry/sentry-cocoa" == 4.3.4
github "Flipboard/FLAnimatedImage" == 1.0.14
github "blissapps/SocketRocket" "carthage-support"

## Problem Description

Integrating the SDK into our own app following the manual configuration documents and using CocoaPod instead of Carthage is causing a crash at runtime:

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSPlaceholderDate initWithYear:month:day:hour:minute:second:]: unrecognized selector sent to instance 0x2823d8080'
*** First throw call stack:
(0x22dc0e98c 0x22cde79f8 0x22db2b1c8 0x22dc141d4 0x22dc15e6c 0x100c7c108 0x22cde9ffc 0x22cdebe54 0x101676390 0x101688380 0x1016873dc 0x101687498 0x1016766d8 0x10167b2a0 0x101675044)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

## Solution

Manual integration documentation is missing configuration settings.
This issue is solved by adding ```-all_load``` or ```-force_load``` to the Other Linker Flags (```OTHER_LDFLAGS```) build setting.
See https://developer.apple.com/library/archive/qa/qa1490/_index.html for more details.

**Comment by aare-undo-idnow** [comment]
Closing this as it will be solved when with #31. 

And yes, I do realise this is two and a half years old. But still.
