### ISSUE TITLE
iOS13 IDnowSettings.modalPresentationStyle ignored for legitimation screen

### ISSUE THREAD

**Issue by thekie** [idnow/de.idnow.ios#63]
Hello,
I found misbehavior in iOS 13.
Currently, the default `modalPresentationStyle` is set to `.pageSheet` and I personally don't think Apple will change that anymore.

Therefore we had to set the `modalPresentationStyle` in our code explicitly to `.fullScreen`. Which I also tried for the `IDnowController` using the `IDnowSettings.modalPresentationStyle` property.

```swift
let settings = IDnowSettings()
settings.modalPresentationStyle = .fullScreen
settings.showErrorSuccessScreen = false
settings.showVideoOverviewCheck = false
// some other stuff ...
idnowController = IDnowController.init(settings: settings)
idnowController?.initialize(completionBlock: { [weak self] (success, error, canceled) in
// and so on …
```

Unfortunately, this setting has no effect on the presentation for the legitimation view controller after the connectivity check. The legitimation view controller is still presented using the `modalPresentationStyle` `.pageSheet.

Could you please have a look into that?

**Comment by danielkiedrowski** [comment]
Still experiencing this with iOS13 GM Seed.

**Comment by phu-idnow** [comment]
hi @danielkiedrowski ,
From iOS 13, Apple changed modalPresentationStyle `.pageSheet` instead of `.fullScreen`.
The team is updating it.

Thanks for mentioned that.

**Comment by danielkiedrowski** [comment]
I know. That’s why I try to set it with your exposed setter. :)

---
Daniel Kiedrowski
Levire UG (haftungsbeschränkt) & Co. KG 
+49 157 789 126 86
daniel@levire.com

(Sent from mobile. Please excuse autocorrection errors and brevity.)

**Comment by pietrobasso** [comment]
Same issue as described here! https://github.com/idnow/de.idnow.ios/issues/73
