### ISSUE TITLE
Cannot build with xcode 11

### ISSUE THREAD

**Issue by alxndr-k** [idnow/de.idnow.ios#65]
It is not possible to build an app with IDNow SDK linked via pods.

Xcode throws the following error:
<img width="1109" alt="Screenshot 2019-09-12 at 12 44 38" src="https://user-images.githubusercontent.com/2167961/64778061-9892ab80-d55b-11e9-8dcd-4d326bad8053.png">

It is a known issue from cocoapods. One solution that can/should be applied from your side mentioned here: https://github.com/CocoaPods/CocoaPods/issues/8431 - it is necessary to use `resource_bundles`.

You can easily reproduce the issue: create a new project and add IDnow via pods.

SDK version: 3.21.0
Xcode version: 11.0 (11A419c)
macOS: 10.14.6 (18G95)

**Comment by phu-idnow** [comment]
hi,

You can fix that by changing the Build System to Legacy one instead of New one.

![hdaJu](https://user-images.githubusercontent.com/42606414/65014397-ce170a80-d948-11e9-8828-540720e3579e.png)


Thanks,

**Comment by alxndr-k** [comment]
@phu-idnow Thank you for the reply. Unfortunately switching to "Legacy Build System" sounds like a wrong way to go. The name itself says that you shouldn't use it.

Is there anything else you or we can do, in order to solve it properly?

**Comment by kondratk** [comment]
The main con with legacy build system is that you will loose parallelization of the build, which will result with longer build times and bigger occupancy of CI/CD systems. We are also struggling with that error, and legacy build system is not a go for us.

**Comment by matijakregar** [comment]
@phu-idnow Is supporting SPM on the roadmap? With Xcode 11 this seems to be the preferred way to include external dependencies.

**Comment by GrigoryShushakov** [comment]
@phu-idnow Any updates on that?

**Comment by dyrkabes** [comment]
@phu-idnow any update on that? Still the same after the latest release

**Comment by cloudtrust-private** [comment]
https://github.com/dreampiggy/cocoapods-xcode-patch
There is a plugin developed by the Cocoapods community that can solve this issue.

**Comment by cedric-elca** [comment]
https://github.com/dreampiggy/cocoapods-xcode-patch
This plugin developed by the Cocoapods community can solve this issue.

**Comment by AlonsoFloo** [comment]
@phu-idnow any update ?

**Comment by phu-idnow** [comment]
hi everyone, 
The team already fixed this. so we can build with the `New build system` now. 
please check the newest version (4.1.5)

Thanks,
