### ISSUE TITLE
Getting stuck on `Signature canceled` view

### ISSUE THREAD

**Issue by bkucharskiDev** [idnow/de.idnow.ios#67]
After cancelling documentation signing I get stuck on `Signature canceled` view. I have read all migration guides and did all required steps. I have upgraded from version 3.5.0 (which was working as expected) to 3.22.0.

Version: 3.22.0
iOS 12.4.1

**Comment by bkucharskiDev** [comment]
Also after relaunching the app I cannot finish next idnow session. This time I get stuck on `Einen Moment Geduld...` screen and get `EXISTING_IDENTIFICATION` error after starting it.

**Comment by phu-idnow** [comment]
hi @bkucharskiDev ,
Did you try another token? or use that token with our Video-ident app on AppStore.
For quick support, you can create a ticket via support.idnow.io.

Thanks,

**Comment by bkucharskiDev** [comment]
I didn't try another token because for the same user idnow returns every time the same token. But I have tried another token with another user and nothing changes. I have used that token with your app video-ident and the situation occurs again. I have got stuck on `Einen Moment Geduld...` view. This issue only occurs after trying to cancel signature (which doesn't succeed and I got stuck).

**Comment by phu-idnow** [comment]
hi @bkucharskiDev,
I am not sure that I can understand correctly.
It will be good if you attach some screenshots it makes easy to figure out the issue.
can you please create a ticket via support.idnow.io? 

Thanks,

**Comment by bkucharskiDev** [comment]
Here are screenshots with views that I get stuck on. We created a ticket via support.idnow.io on Oct. 25th (DESK-11961) and haven't received any answer yet. @phu-idnow can you ping your support to start helping us?

![IMG_1180](https://user-images.githubusercontent.com/31849847/67752479-54883700-fa33-11e9-8022-30812aa09807.JPG)
![IMG_1182](https://user-images.githubusercontent.com/31849847/67752481-5520cd80-fa33-11e9-8072-1cf3bb6c3190.JPG)

**Comment by phu-idnow** [comment]
Hi @bkucharskiDev ,
We checked that, it's our robot issue, not iOS. Please try with another test
ps: also commented on the ticket.
Thanks,

**Comment by aare-undo-idnow** [comment]
*Crickets*

Looks resolved. Closing
