### ISSUE TITLE
idnow not working on iOS 13 nor on macbook

### ISSUE THREAD

**Issue by cs224** [idnow/de.idnow.ios#69]
I am an end-user and wanted to use IDnow for verifiying my identity to open a new bank account. I tried to make it work several times via different iPhones and different WLANs, but no luck. The comment of the operator was always: the connection is not working / the video and audio sync is not working.

I used IDnow previously on my iPhone in the same WLAN and it worked then. So I guess it has something to do with the iOS version.

I also tried to use a MacBook, but the info of the operator was simply that the resolution is not good enough. I wonder why IDnow even offers that option if it anyway will not work?

**Comment by phu-idnow** [comment]
I am not sure I can understand completely. For quick support, can you please create a ticket via support.idnow.de

Thanks
