### ISSUE TITLE
Crash in App and fixes only removing and installing again

### ISSUE THREAD

**Issue by joselinoneto** [idnow/de.idnow.ios#72]
hello guys,

we are facing some crashes above the logs.
when it happens will be recurring until delete the app and install again:

2019-11-19 15:12:08.449656+0000 i9 QA[400:22603] customer-config call: https://api.test.idnow.de/api/v1/HEREWILLBEMYKEY:D
2019-11-19 15:12:09.843331+0000 i9 QA[400:22603] ask for messages: https://go.test.idnow.de/assets/messages.json?shortName=HEREWILLBEMYKEY:D
2019-11-19 15:12:13.887319+0000 i9 QA[400:22603] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** __boundsFail: index 3 beyond bounds [0 .. 2]'
*** First throw call stack:
(0x1862c498c 0x185fed0a4 0x18631a3f8 0x18632411c 0x1861b183c 0x193400108 0x193402d38 0x1057ea60c 0x1057ea164 0x1050f8990 0x113b24364 0x113b24564 0x113b3ccd4 0x113b253c0 0x113b2567c 0x113b3b99c 0x113b2e730 0x113b0dfa0 0x113b0cc44 0x116986c04 0x116989808 0x11699ca54 0x116994ad4 0x1862423c4 0x18623d3b8 0x18623c8bc 0x1900a8328 0x18a2d26d4 0x104cd6598 0x1860c7460)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by phu-idnow** [comment]
hi @joselinoneto jo,
Please go to `Build Settings/Other Linker Flags` and add `-ObjC` 

Thanks,

**Comment by tjanela** [comment]
Hey @phu-idnow, it turns out this issue was not related to your SDK, in the first place. I believe this issue can be closed.

I strongly suggest adding the -ObjC flag to the documentation. We faced that issue and, if not for our accumulated experience, we would have spent considerable effort figuring out what to do.

Thank you for your time.

**Comment by phu-idnow** [comment]
yes, then can you please close the issue?

Thanks,
