### ISSUE TITLE
Linking fails due to duplicate symbols fm.o (4.0.0)

### ISSUE THREAD

**Issue by tjanela** [idnow/de.idnow.ios#74]
Xcode: 11.0
macOS: 10.15.1
IDnow: 4.0.0
Manual integration

We are getting a total of 31 duplicate symbols:
```
duplicate symbol '_ConvertIntArray' in:
    /Users/tjanela/Code/i9-ios/SDKs/idnow-sdk/libidnow-sdk-universal.a(fm.o)
```
This occurs compiling for any destination:
`ld: 31 duplicate symbols for architecture x86_64`
`ld: 31 duplicate symbols for architecture arm64`

These symbols come from the IceLink library that you updated on 4.0.0

We would like to give 4.0.0 a try but can't until this is sorted out.

**Comment by tjanela** [comment]
I also opened a ticket on JIRA, the same title as this one.

**Comment by phu-idnow** [comment]
duplicate? it seems reference twice?

Could you give me the ticket number?

Thanks,

**Comment by phu-idnow** [comment]
ah, Manual integration.
you can follow this guide: https://stackoverflow.com/a/24300502/6683634

**Comment by tjanela** [comment]
@phu-idnow if I remove -ObjC then:
Undefined symbols for architecture x86_64:
  "_VTCompressionSessionInvalidate", referenced from:
      -[FMIceLinkCocoaVideoToolboxH264Encoder receiveEnterForegroundNotification:] in libidnow-sdk-universal.a(FMIceLinkCocoaVideoToolboxH264Encoder.o)
      -[FMIceLinkCocoaVideoToolboxH264Encoder encodeWithBuffer:frame:outputFormat:] in libidnow-sdk-universal.a(FMIceLinkCocoaVideoToolboxH264Encoder.o)
      -[FMIceLinkCocoaVideoToolboxH264Encoder destroy] in libidnow-sdk-universal.a(FMIceLinkCocoaVideoToolboxH264Encoder.o)
  "_kVTCompressionPropertyKey_MaxH264SliceBytes", referenced from:
      -[FMIceLinkCocoaVideoToolboxH264Encoder createCompressionSessionWithWidth:height:pixelBufferSpec:output:] in libidnow-sdk-universal.a(FMIceLinkCocoaVideoToolboxH264Encoder.o)
  "_kVTEncodeFrameOptionKey_ForceKeyFrame", referenced from:
      -[FMIceLinkCocoaVideoToolboxH264Encoder encodeWithBuffer:frame:outputFormat:] in libidnow-sdk-universal.a(FMIceLinkCocoaVideoToolboxH264Encoder.o)
  "_kVTCompressionPropertyKey_RealTime", referenced from:
      -[FMIceLinkCocoaVideoToolboxH264Encoder createCompressionSessionWithWidth:height:pixelBufferSpec:output:] in libidnow-sdk-universal.a(FMIceLinkCocoaVideoToolboxH264Encoder.o)
  "_kVTCompressionPropertyKey_MaxKeyFrameInterval", referenced from:
      -[FMIceLinkCocoaVideoToolboxH264Encoder createCompressionSessionWithWidth:height:pixelBufferSpec:output:] in libidnow-sdk-universal.a(FMIceLinkCocoaVideoToolboxH264Encoder.o)
  "_kVTCompressionPropertyKey_ExpectedFrameRate", referenced from:
      -[FMIceLinkCocoaVideoToolboxH264Encoder createCompressionSessionWithWidth:height:pixelBufferSpec:output:] in libidnow-sdk-universal.a(FMIceLinkCocoaVideoToolboxH264Encoder.o)
  "_VTCompressionSessionCompleteFrames", referenced from:
      -[FMIceLinkCocoaVideoToolboxH264Encoder receiveEnterForegroundNotification:] in libidnow-sdk-universal.a(FMIceLinkCocoaVideoToolboxH264Encoder.o)
      -[FMIceLinkCocoaVideoToolboxH264Encoder destroy] in libidnow-sdk-universal.a(FMIceLinkCocoaVideoToolboxH264Encoder.o)
  "_kVTCompressionPropertyKey_ProfileLevel", referenced from:
      -[FMIceLinkCocoaVideoToolboxH264Encoder createCompressionSessionWithWidth:height:pixelBufferSpec:output:] in libidnow-sdk-universal.a(FMIceLinkCocoaVideoToolboxH264Encoder.o)
  "_VTCompressionSessionEncodeFrame", referenced from:
      -[FMIceLinkCocoaVideoToolboxH264Encoder encodeWithBuffer:frame:outputFormat:] in libidnow-sdk-universal.a(FMIceLinkCocoaVideoToolboxH264Encoder.o)
  "_VTCompressionSessionCreate", referenced from:
      -[FMIceLinkCocoaVideoToolboxH264Encoder createCompressionSessionWithWidth:height:pixelBufferSpec:output:] in libidnow-sdk-universal.a(FMIceLinkCocoaVideoToolboxH264Encoder.o)
  "_kVTProfileLevel_H264_Baseline_3_1", referenced from:
      -[FMIceLinkCocoaVideoToolboxH264Encoder createCompressionSessionWithWidth:height:pixelBufferSpec:output:] in libidnow-sdk-universal.a(FMIceLinkCocoaVideoToolboxH264Encoder.o)
  "_VTSessionSetProperty", referenced from:
      -[FMIceLinkCocoaVideoToolboxH264Encoder createCompressionSessionWithWidth:height:pixelBufferSpec:output:] in libidnow-sdk-universal.a(FMIceLinkCocoaVideoToolboxH264Encoder.o)
      -[FMIceLinkCocoaVideoToolboxH264Encoder doProcessFrame:inputBuffer:] in libidnow-sdk-universal.a(FMIceLinkCocoaVideoToolboxH264Encoder.o)
  "_VTDecompressionSessionCanAcceptFormatDescription", referenced from:
      -[FMIceLinkCocoaVideoToolboxH264Decoder decodeWithEncodedFrame:frame:outputFormat:] in libidnow-sdk-universal.a(FMIceLinkCocoaVideoToolboxH264Decoder.o)
  "_kVTCompressionPropertyKey_AllowFrameReordering", referenced from:
      -[FMIceLinkCocoaVideoToolboxH264Encoder createCompressionSessionWithWidth:height:pixelBufferSpec:output:] in libidnow-sdk-universal.a(FMIceLinkCocoaVideoToolboxH264Encoder.o)
  "_VTDecompressionSessionDecodeFrame", referenced from:
      -[FMIceLinkCocoaVideoToolboxH264Decoder decodeWithEncodedFrame:frame:outputFormat:] in libidnow-sdk-universal.a(FMIceLinkCocoaVideoToolboxH264Decoder.o)
  "_kVTCompressionPropertyKey_AverageBitRate", referenced from:
      -[FMIceLinkCocoaVideoToolboxH264Encoder createCompressionSessionWithWidth:height:pixelBufferSpec:output:] in libidnow-sdk-universal.a(FMIceLinkCocoaVideoToolboxH264Encoder.o)
      -[FMIceLinkCocoaVideoToolboxH264Encoder doProcessFrame:inputBuffer:] in libidnow-sdk-universal.a(FMIceLinkCocoaVideoToolboxH264Encoder.o)
  "_VTDecompressionSessionCreate", referenced from:
      -[FMIceLinkCocoaVideoToolboxH264Decoder createDecompressionSessionWithFormatDescription:output:] in libidnow-sdk-universal.a(FMIceLinkCocoaVideoToolboxH264Decoder.o)
  "_VTDecompressionSessionInvalidate", referenced from:
      -[FMIceLinkCocoaVideoToolboxH264Decoder receiveEnterForegroundNotification:] in libidnow-sdk-universal.a(FMIceLinkCocoaVideoToolboxH264Decoder.o)
      -[FMIceLinkCocoaVideoToolboxH264Decoder decodeWithEncodedFrame:frame:outputFormat:] in libidnow-sdk-universal.a(FMIceLinkCocoaVideoToolboxH264Decoder.o)
      -[FMIceLinkCocoaVideoToolboxH264Decoder destroy] in libidnow-sdk-universal.a(FMIceLinkCocoaVideoToolboxH264Decoder.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by tjanela** [comment]
@idnow @souheib93 @phu-idnow your manual installation documentation needs to be written and updated accordingly.
Not everybody uses CocoaPods, Carthage, SPM, or any dependency manager.
You should always start by documenting manual integrations. Do you need help with this?
This is proprietary commercial software... and the lack of these documents is costing me and my clients money.

To whoever comes across this issue there are a number of dependencies that are only listed in this framework podspec:
https://github.com/CocoaPods/Specs/blob/master/Specs/b/2/e/IDnowSDK/4.1.1/IDnowSDK.podspec.json

Here is the list:
- StoreKit
- Accelerate
- WebKit
- AudioToolbox
- AVFoundation
- CoreMedia
- GLKit
- OpenGLES
- SystemConfiguration
- UserNotifications
- VideoToolbox
