### ISSUE TITLE
What is IDnowAppDelegate for?

### ISSUE THREAD

**Issue by Beniamiiin** [idnow/de.idnow.ios#75]
Hi, I'd like to know what kind of notifications do you send? Also, is it possible to know the current position in the queue and when an agent connected?

**Comment by phu-idnow** [comment]
hi @Beniamiiin ,
There are 2 types of notifications, SMS or push. Currently, user doesn't know where they are in the queue. 

> When an agent connected? 

--> When they receive SMS/push notification, notify their identifications can start. 
Thanks,

**Comment by Beniamiiin** [comment]
I want to show a screen "Waiting for an agent" with my own design above SDK screen and when an agent will be connected I just want to dismiss my screen and then a user can speak with an agent. I thought that I can do it via handling push notifications. Am I right or not? Or maybe the SDK has another way to do it?

**Comment by phu-idnow** [comment]
hi, 
Currently, IDNow SDK is showing "Waiting for an agent" and all relevant statuses for the call.
Yes, you can do it via push notification, I think. or if you need a specific requirement just open a request, the team will try to investigate it.

Thanks,

**Comment by Beniamiiin** [comment]
Thanks for your quick response.

> Currently, IDNow SDK is showing "Waiting for an agent" and all relevant statuses for the call.
Do you mean that the SDK show statuses on the SDK screen? But maybe it possible to get all relevant statuses via delegate/callbacks or in some other way?

My problem is that I want to create my own "Waiting for an agent" screen and show the SDK screen only when an agent was successfully connected. So I need some API to know when it happened.

**Comment by Beniamiiin** [comment]
@phu-idnow so can you help me?

**Comment by phu-idnow** [comment]
that's a good idea. Can you please create a ticket via support.idnow.de. The team will investigate and plan to do it later.

Thanks,

**Comment by Beniamiiin** [comment]
@phu-idnow I've created the ticket(DESK-13626). I'll look forward to any news.
