### ISSUE TITLE
Provide flag whether to open Safari for startIdentificationFromViewController

### ISSUE THREAD

**Issue by phoboslab** [idnow/de.idnow.ios#78]
Referencing https://github.com/idnow/de.idnow.ios/issues/32 and https://github.com/idnow/de.idnow.ios/issues/34 - this is surprising behavior that should at least be documented. Apparently we are not the first ones stumbling over this issue.

However, I would argue that a separate flag in `IDnowSettings` makes more sense than a backend configuration, as we need to control this behavior on a per-app basis, not globally for "web" or "app" environments.

**Comment by aare-undo-idnow** [comment]
I apologise that your concerns weren't addressed when they should have been, however, this is now more than two years old and no longer relevant. Closing.
