### ISSUE TITLE
SDK causes terrifying noise on Simulator

### ISSUE THREAD

**Issue by boennemann** [idnow/de.idnow.ios#79]
After upgrading to version 4 of the SDK our entire team is experiencing a terrifying noise on the iOS simulator as soon as we open the SDK.

We're not observing this on real devices.

Please have a look into this.

**Comment by mreichelt** [comment]
Happened to me as well 👋

**Comment by phu-idnow** [comment]
hi @boennemann,
Thanks for pointing this. Could you give us the SDK version (4.?.?) and Xcode version you are using?

Thanks,

**Comment by aare-undo-idnow** [comment]
Closing as I have no idea what this is. Gave me a good laugh, though.
