### ISSUE TITLE
OpenTok + OpenSSL problems

### ISSUE THREAD

**Issue by kmikael** [idnow/de.idnow.ios#8]
`OpenTok` is linked with an OpenSSL fork, which means that apps that use OpenSSL can't be cleanly linked with OpenSSL and IDnowSDK https://twitter.com/tokbox/status/621020769716342784

I don't know if there is a solution to this problem, but I just wanted you to know it exists.

**Comment by kmikael** [comment]
As of at least OpenTok 2.6.0 this has somehow been fixed. We were able to add OpenTok and our OpenSSL of choice both to the project without problems.

**Comment by macmacen** [comment]
Thanks for the info.
We have to do some more testing for that. But IDnow will also update to the newest OpenTok version in short.

**Comment by arminbauer** [comment]
A new version with updated OpenTok libraries is available at https://github.com/idnow/de.idnow.ios/releases/download/de.idnow.ios-2.0.0-RC.2/idnow-ios-2.0.0-RC.2.zip
