### ISSUE TITLE
Not all text resources can be localized

### ISSUE THREAD

**Issue by RiRomain** [idnow/de.idnow.ios#84]
When localizing the app to Dutch, via file:
IDnowSDK/idnow-sdk/resources/IDnowSDKLocalization.bundle/nl.lproj/Localizable.strings
some resource localisation are not successful.

For example setting a new text for resource INFO_CONNECTING_DESCRIPTION doesn't have an effect and the default English text is still being used:
![image](https://user-images.githubusercontent.com/10770933/77178647-aa837700-6ac7-11ea-91d1-f11832ecf57e.png)

In addition, the speed test seems to always be displayed in English.

**Comment by phu-idnow** [comment]
hi @RiRomain ,
This also depends on customer configuration. it will override most of the localized keys.
so please make sure the testing language included in your customer configuration.

Thanks,
Phu

**Comment by aare-undo-idnow** [comment]
Localizations have changed somewhat in 1.5 years and this specific question is no longer relevant. Closing the issue. If new localization issues pop up, please do report them right here!
