### ISSUE TITLE
cannot dismiss IDnowController modally presented on iOS 12

### ISSUE THREAD

**Issue by mpatafio** [idnow/de.idnow.ios#86]
Hi!
I'm using  **de.idnow.ios-4.1.2**.

I need to always present modally the IDnowController. On iOS 13 the default presentation style allows the user to swipe down to close the presented view controller, on iOS 12 instead I need to make the back (cancel) button appear (instantiating a `UIBarButtonItem` and assigning it to the property `customBackButtonItem` of the `IDnowAppearance sharedAppearance`). This assignment makes the button appear

![Simulator Screen Shot - iPhone 8 - 2020-04-15 at 09 12 41](https://user-images.githubusercontent.com/6072188/79309801-2e7c2380-7efb-11ea-8018-5b71d1beef11.png)

 but the properties `target` and `action` I assign to the  `UIBarButtonItem` instance this way:

`[[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemCancel target:self action:@selector(dismissVC)];` 

will be always overridden like this:

<img width="563" alt="Screenshot 2020-04-15 at 09 01 30" src="https://user-images.githubusercontent.com/6072188/79309069-fcb68d00-7ef9-11ea-8bb9-7567b19f6dbc.png">

I guess that the `handleBack:` selector you're using probably doesn't support the dismiss of modally presented view controller.  Is that correct? Do I have to use different solutions to make the view controller being dismissed?
 

Thanks in advance

**Comment by andrejcesen** [comment]
We're experiencing the same issue as well when building with Xcode 11.

**Comment by andrejcesen** [comment]
The latest version `1.4.5` does indeed pertain the `target` and `action` set by
`[[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemCancel target:self action:@selector(dismissVC)];`
but still my handler `dismissVC` is not being called.

@mpatafio Have you managed to find any solution to this issue?

**Comment by mpatafio** [comment]
Hi @andrejcesen do you mean version **4.1.5**?

I think that, by design, the sdk  allows you to customise appearance only for the `customBackButtonItem` (in facts it overrides properties target with an internal instance of tableview and the action with its internal `handleBack:` method). Here I guess the issue is related to the internal sdk implementation of the `handleBack:` method that is not correctly handling the fact that the view contoller can be pushed or presented modally.

**Comment by andrejcesen** [comment]
@mpatafio Yeah, my bad, I meant **4.1.5**. So this version actually **does not** override the `target` and `action` properties, but tapping the button still doesn't call my `dismissVC` method. 🤔

**Comment by mpatafio** [comment]
Hi @andrejcesen how do you customise this button? Because even with version **4.1.5** I still see properties overridden

**Comment by andrejcesen** [comment]
Hey @mpatafio,

This is the setup code I use to configure `[IDnowAppearance sharedAppearance]`:

`[IDnowAppearance sharedAppearance].customBackButtonItem = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemCancel target:self action:@selector(dismissVC)];`

`NSLog(@"customBackButtonItem: %@", appearance.customBackButtonItem);`

![a1a7647e-2855-47e0-be1d-2f1c7a7a0a08](https://user-images.githubusercontent.com/1460733/80695457-3da3c980-8ad6-11ea-9f9a-bfb69f84b012.png)

**Comment by mpatafio** [comment]
Thanks @andrejcesen!

I see, but I guess it depends on when you do 
`[IDnowAppearance sharedAppearance].customBackButtonItem = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemCancel target:self action:@selector(dismissVC)];` 

do you perform such customisation AFTER or BEFORE the IDnow controller being presented? Because what I encountered is that:
- if you do it BEFORE the appearance is correctly customised (target and action are overridden) - this is probably the right timing for the SDK in order to properly render such component.
- if you do it AFTER everything is kept as your customisation, but the appearance is NOT correctly customised (due to the fact that the rendering runtimes are gone - e.g. viewDidLoad and so on)

**Comment by andrejcesen** [comment]
Hey @mpatafio,

I do customization **before** presenting IDnowController and printing the properties shows `target` and `action` as being correctly customized.

I suspect the customized `UIBarButtonItem` is added in `init` / `viewDidLoad:` method, so customizing it after the view controller is presented probably misses the opportunity to adjust it.

Did the SDK behave differently prior to version **1.4.5**?

**Comment by phu-idnow** [comment]
> Hi!
> I'm using **de.idnow.ios-4.1.2**.
> 
> I need to always present modally the IDnowController. On iOS 13 the default presentation style allows the user to swipe down to close the presented view controller, on iOS 12 instead I need to make the back (cancel) button appear (instantiating a `UIBarButtonItem` and assigning it to the property `customBackButtonItem` of the `IDnowAppearance sharedAppearance`). This assignment makes the button appear
> 
> ![Simulator Screen Shot - iPhone 8 - 2020-04-15 at 09 12 41](https://user-images.githubusercontent.com/6072188/79309801-2e7c2380-7efb-11ea-8018-5b71d1beef11.png)
> 
> but the properties `target` and `action` I assign to the `UIBarButtonItem` instance this way:
> 
> `[[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemCancel target:self action:@selector(dismissVC)];`
> 
> will be always overridden like this:
> 
> <img alt="Screenshot 2020-04-15 at 09 01 30" width="563" src="https://user-images.githubusercontent.com/6072188/79309069-fcb68d00-7ef9-11ea-8bb9-7567b19f6dbc.png">
> 
> I guess that the `handleBack:` selector you're using probably doesn't support the dismiss of modally presented view controller. Is that correct? Do I have to use different solutions to make the view controller being dismissed?
> 
> Thanks in advance

yes, you're correct. currently, it uses for pop back the previous screen in the navigation stack only.

**Comment by andrejcesen** [comment]
> yes, you're correct. currently, it uses for pop back the previous screen in the navigation stack only.

@phu-idnow When building with Xcode 10, the IDnow Controller gets pushed to my navigation stack, so everything is working as it should.

**But when building with Xcode 11, this screen gets presented modally, no matter the settings.** When the app (built with Xcode 11) is run on iOS 12 device, there is no way of dismissing IDnow Controller, since:
1. it doesn't push it onto the existing navigation stack, and
2. is instead presented in fullscreen modal with no way of navigating back.

What is the solution to make IDnow controller dismissible?

**Comment by pavel-antonov-idnow** [comment]
Hi @andrejcesen , sorry for delay.

> But when building with Xcode 11, this screen gets presented modally, no matter the settings

does view controller who presents the modal has navigationController ?

**Comment by andrejcesen** [comment]
@pavel-antonov-idnow Correct, presenting view controller is a (subclass of) UINavigationController. As I said, this works as expected when building with Xcode 10, but not when building with Xcode 11.

Perhaps the best way to solve this is to enable consumers of IDnow SDK to specify their own custom `UIBarButtonItem` when presenting IDnow Controller (which is already possible), but there is a bug with handling events - even handler is not called:

> The latest version **1.4.5** does indeed pertain the `target` and `action` set by
> 
> `[[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemCancel target:self action:@selector(dismissVC)];`
> 
> but still my handler `dismissVC` is not being called.
> 
> @mpatafio Have you managed to find any solution to this issue?

Let me know if you need any additional information to debug this.

Best regards,
Andrej

**Comment by pavel-antonov-idnow** [comment]
@andrejcesen thank you
 I'm workin on the solution hope the fix will be included in one of the closest releases

**Comment by andrejcesen** [comment]
@pavel-antonov-idnow Perfect, thanks. :)

**Comment by pavel-antonov-idnow** [comment]
resolved with 4.1.7 release

**Comment by mpatafio** [comment]
Just checked, it works as expected. Thanks!
