### ISSUE TITLE
Confusing Git tags and release names

### ISSUE THREAD

**Issue by sonicdoe** [idnow/de.idnow.ios#89]
For the latest release, v4.1.7, there are two Git tags: [`de.idnow.ios-4.1.7`](https://github.com/idnow/de.idnow.ios/releases/tag/de.idnow.ios-4.1.7) and [`de.idnow.android-4.1.7`](https://github.com/idnow/de.idnow.ios/releases/tag/de.idnow.android-4.1.7) (even though this is the iOS repository).

Furthermore, for v4.1.6 and v4.1.5, the tags are [`de.idnow.ios-4.1.6`](https://github.com/idnow/de.idnow.ios/releases/tag/de.idnow.ios-4.1.6) and [`de.idnow.ios-4.1.5`](https://github.com/idnow/de.idnow.ios/releases/tag/de.idnow.ios-4.1.5) but the releases themselves are named `de.idnow.android-4.1.6` and `de.idnow.android-4.1.5`, respectively.

**Comment by phu-idnow** [comment]
hi,
Thank you very much for pointing this out. The team will fix that.

Thanks,

**Comment by phu-idnow** [comment]
hi @sonicdoe,
FYI: Team fixed that!

Thanks,
