### ISSUE TITLE
Update lottie-ios dependency 

### ISSUE THREAD

**Issue by p-janik** [idnow/de.idnow.ios#92]
Hey guys 👋

Do you think it would be possible to update [lottie-ios](https://github.com/CocoaPods/Specs/blob/de9dc4c22926c3d8ac1a453545da37a738d37fdb/Specs/b/2/e/IDnowSDK/4.3.0/IDnowSDK.podspec.json#L62-L64) to newer version? The current used is [from March 2019](https://github.com/airbnb/lottie-ios/releases/tag/2.5.3).

We use react-native-lottie and it causes issues with our another dependancy, `lottie-react-native` which uses `lottie-ios 3.1.3` under the hood.

This is what I get when I try to update to  **IDnow 4.3.1** from **4.2.4**:
```
[!] CocoaPods could not find compatible versions for pod "lottie-ios":
  In snapshot (Podfile.lock):
    lottie-ios (from `../node_modules/lottie-ios`)

  In Podfile:
    IDnowSDK (= 4.3.1) was resolved to 4.3.1, which depends on
      lottie-ios (~> 2.5)

    lottie-ios (from `../node_modules/lottie-ios`)

    lottie-react-native (from `../node_modules/lottie-react-native`) was resolved to 3.3.2, which depends on
      lottie-ios (~> 3.1.3)
```

**Comment by sasha-tomorrow** [comment]
Actually, I would question the need of such dependencies in library that are integrated by other apps. It brings unnecessary dependencies to other apps. You should keep your footprint as small as possible, though it seems you just adding new libraries.

So IDNow, can you please remove this library completely?

**Comment by pavel-antonov-idnow** [comment]
@p-janik We stick to 2.5.3 as the latest and recommended version of Lottie for obj-c projects. 

@p-janik @sasha-tomorrow  I'll research what we can do to make the sdk easier for integration

**Comment by kondratk** [comment]
Same here. Swift codebase, so using latest lottie.
@pavel-antonov-idnow cant you just use bridging header to use latest lottie with objc codebase?

**Comment by kondratk** [comment]
@sasha-tomorrow absolutely agree. Same thing with Sentry- it is not responsibility of 3rd party library to log crashes.

**Comment by pavel-antonov-idnow** [comment]
update: Lottie version will be updated in future releases. Probably early January.

**Comment by pavel-antonov-idnow** [comment]
Lottie functionality incapsulated to the sdk since [4.5.2](https://github.com/idnow/de.idnow.ios/releases/tag/de.idnow.4.5.2)  so no more Lottie dependency.

**Comment by p-janik** [comment]
@pavel-antonov-idnow thanks I see it working now. 

I see that with version 4.5.1 you have introduced `Countly`. Is that tracking dependency really required?
