### ISSUE TITLE
error: linker command failed Undefined symbols for architecture x86_64:

### ISSUE THREAD

**Issue by java350** [idnow/de.idnow.ios#94]
Hey IDNow iOS team 👋

When using version 4.3.0 to 4.4.1, I get an error during build, can you help solve this error?
on version 4.2.4 - no error

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_IDnowController", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_IDnowSettings", referenced from:
      objc-class-ref in ViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ernichechelski** [comment]
I got this issue too 🤔

**Comment by ernichechelski** [comment]
> Hey IDNow iOS team 👋
> 
> When using version 4.3.0 to 4.4.1, I get an error during build, can you help solve this error?
> on version 4.2.4 - no error
> 
> Undefined symbols for architecture x86_64:
> "_OBJC_CLASS_$_IDnowController", referenced from:
> objc-class-ref in ViewController.o
> "_OBJC_CLASS_$_IDnowSettings", referenced from:
> objc-class-ref in ViewController.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

Can you provide stack (Xcode version etc) which are you using? 😄

**Comment by java350** [comment]
@ernichechelski 
Xcode Version 12.1 (12A7403)

**Comment by ernichechelski** [comment]
I manage to build successfully with XCode 11.7 and cocoapods version `1.9.3`, however please check below links, maybe i'll be useful for you, as I belive that is more Cocoapods related than library related issue: 😄 
- https://www.jessesquires.com/blog/2020/07/20/xcode-12-drops-support-for-ios-8-fix-for-cocoapods/
- https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-object-file-built-for-ios

**Comment by pavel-antonov-idnow** [comment]
the latest 4.5.2 and 4.2.5 releases now has compatibility with Xcode 12
