### ISSUE TITLE
Countly dependency

### ISSUE THREAD

**Issue by p-janik** [idnow/de.idnow.ios#96]
Hey guys,

Is this kind of dependency mandatory?
Can you describe for what is it used in IDnow SDK?

Thanks!

**Comment by pavel-antonov-idnow** [comment]
Counlty dependency will be removed in next release

**Comment by PavelStepanovTomorrow** [comment]
Not sure if it is the right issue to mention that. But in the current release version we have the error

```
duplicate symbol '_appLoadStartTime' in:
    /Users/pavelstepanov/mobile-ios-app/Pods/IDnowSDK/idnow-sdk/libidnow-sdk-universal.a(Insights.o)
    /Users/pavelstepanov/Library/Developer/Xcode/DerivedData/Tomorrow-gbjcjsfsefjlncgpupqcorygsddc/Build/Products/Debug-iphonesimulator/Countly/Countly.framework/Countly(Countly.o)
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

We are using both Countly and IDNow and I guess that is what creates this conflict. Do you have an idea how we can resolve that? :) 
Thanks

**Comment by pavel-antonov-idnow** [comment]
Hi @PavelStepanovTomorrow do you use 5.0.2 ?

**Comment by pavel-antonov-idnow** [comment]
@p-janik Countly dependency removed

**Comment by PavelStepanovTomorrow** [comment]
@pavel-antonov-idnow yes, exactly:

- IDnowSDK (5.0.2):
- Countly (20.11.1):

For 4.5.2 works fine, for 5.0.2 the build fails with the error. So I guess the issue is that we have Countly 2 times now – probably embedded from IDNow and from our own Countly pod. And those definitions clash

Although I am unfortunately no expert in pods so asking for help :)

**Comment by pavel-antonov-idnow** [comment]
@PavelStepanovTomorrow  did you try to clean the DerivedData folder?

**Comment by pavel-antonov-idnow** [comment]
@PavelStepanovTomorrow this looks like conflict because of the same name of global variables, we will fix it shortly in next release(about two weeks), sorry for the case.
as a workaround can only recommend to rename the variable within Countly until the release:

**Comment by PavelStepanovTomorrow** [comment]
@pavel-antonov-idnow thank you for the lightning fast response :) 
Yes, the renaming helped, although we will wait for the next release due to our internal structure

Thanks again
