### ISSUE TITLE
Install idnow via cocoapods (v5.0)

### ISSUE THREAD

**Issue by b-allard** [idnow/de.idnow.ios#97]
Hi everybody,

We have tried to add the idnow sdk via cocoapods with the last version of the idnow pod (v 5.0). However we have some issues : 

- Some import issues of the libPhoneNumber-iOS pod, some import are not found. Replace all import "****.h" by <****.h> fix the issues
- After that, we have an other issue with "Library not found for -lidnow-sdk-universal"

Please could you help us ?

Thanks in advance, 

Edit : we use Xcode 12.4

**Comment by pavel-antonov-idnow** [comment]
Hi @b-allard sorry for the late response.
Please try with just released 5.0.2 and please provide the log of the import issues

**Comment by aare-undo-idnow** [comment]
Crickets. Looks like it's fixed
